baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Pixelators'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.assets]
theme_color = "#ffffff"
msapplication_TileColor = "#ffffff"