baseURL = 'https://pixelators4014-github-io.pages.dev'
languageCode = 'en-us'
title = 'Pixelators'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"

[params.assets]
theme_color = "#ffffff"
msapplication_TileColor = "#ffffff"

[params.label]
icon = "images/topnav_logo.png"
