baseURL = '/'
languageCode = 'en-us'
title = 'Pixelators'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"

[params.assets]
theme_color = "#ffffff"
msapplication_TileColor = "#ffffff"

[params.label]
icon = "images/logo.avif"
iconHeight = 20

[module]
[[module.imports]]
path = "hugo-notice"
