name: Convert Images to AVIF

on:
  push:
    branches:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Convert images to AVIF
        id: convert_images
        run: |
          converted=false
          find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) ! -path "./static/*" -exec sh -c '
            for img; do
              avif="${img%.*}.avif"
              if [ ! -f "$avif" ]; then
                convert "$img" "$avif"
                converted=true
              fi
            done
          ' sh {} +
          echo "::set-output name=converted::$converted"

      - name: Create Pull Request
        if: steps.convert_images.outputs.converted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Convert images to AVIF"
          body: "This PR converts all images to AVIF format."
