name: Convert Images to AVIF

on:
  push:
    branches:
      - "*"

permissions:
  pull-requests: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert images to AVIF
        run: |
          find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) ! -path "./static/*" -exec sh -c '
            for img; do
              avif="${img%.*}.avif"
              convert "$img" "$avif"
            done
          ' sh {} +

      - name: Create branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b convert-images-to-avif
          git add .
          git commit -m "Convert images to AVIF format"
          git push --set-upstream origin convert-images-to-avif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Convert images to AVIF format
          branch: convert-images-to-avif
          title: Convert images to AVIF format
          body: This PR converts all JPG, JPEG, PNG, and WEBP images to AVIF format.
